# Generated by Django 3.2.18 on 2023-04-24 15:43

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bldgid', models.CharField(max_length=10)),
                ('currcode', models.CharField(max_length=10)),
                ('fields', models.JSONField(null=True)),
            ],
            options={
                'verbose_name': 'Plantilla',
                'verbose_name_plural': 'Plantillas',
                'db_table': 'templates',
                'ordering': ['bldgid', 'currcode'],
            },
        ),
        migrations.CreateModel(
            name='TemplateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='Null', max_length=30)),
                ('bldgid', models.CharField(max_length=10)),
                ('batch', models.CharField(default='Null', max_length=8)),
                ('invoice_date', models.DateField(default=datetime.date.today)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Registro de Plantillas',
                'verbose_name_plural': 'Registros de Plantillas',
                'db_table': 'templates_log',
                'ordering': ['bldgid', 'batch'],
            },
        ),
        migrations.CreateModel(
            name='TemplateMonthlyCfg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date', models.DateField()),
            ],
            options={
                'verbose_name': 'Ajuste de plantilla',
                'verbose_name_plural': 'Ajustes de plantillas',
                'db_table': 'templates_monthly_config',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='TemplateMonthlyCfgLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('rate', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='plantillas.templatemonthlycfg')),
            ],
            options={
                'verbose_name': 'Resgistro de ajuste de plantilla',
                'verbose_name_plural': 'Resgistros de ajustes de plantillas',
                'db_table': 'templates_monthly_config_log',
                'ordering': ['created'],
            },
        ),
    ]
