# Generated by Django 3.2.18 on 2023-05-11 14:21

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bldgid', models.CharField(max_length=10)),
                ('currcode', models.CharField(max_length=10)),
                ('inccat', models.CharField(default='NULL', max_length=10)),
                ('descrptn', models.CharField(default='NULL', max_length=50)),
                ('descrptn_name', models.CharField(default='NULL', max_length=25)),
            ],
            options={
                'verbose_name': 'Plantilla',
                'verbose_name_plural': 'Plantillas',
                'db_table': 'templates',
                'ordering': ['bldgid', 'currcode'],
            },
        ),
        migrations.CreateModel(
            name='TemplateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='Null', max_length=30)),
                ('bldgid', models.CharField(max_length=10)),
                ('batch', models.CharField(default='Null', max_length=8)),
                ('rate', models.DecimalField(decimal_places=6, default=1, max_digits=9)),
                ('invoice_date', models.DateField(default=datetime.date.today)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Registro de Plantillas',
                'verbose_name_plural': 'Registros de Plantillas',
                'db_table': 'templates_log',
                'ordering': ['bldgid', 'batch'],
            },
        ),
    ]
