# Generated by Django 3.2.18 on 2023-03-15 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plantilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bldgid', models.CharField(max_length=10)),
                ('currcode', models.CharField(max_length=10)),
                ('inccat', models.CharField(max_length=10)),
                ('descrptn', models.CharField(max_length=30)),
            ],
        ),
    ]
