# Generated by Django 3.2.18 on 2023-05-12 14:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('plantillas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatelog',
            name='invoice_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
