# Generated by Django 3.2.18 on 2023-04-26 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantillas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatemonthlycfg',
            name='rate',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
    ]
