# Generated by Django 3.2.18 on 2023-05-08 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantillas', '0002_alter_templatemonthlycfg_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatelog',
            name='rate',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=9),
        ),
    ]
