# Generated by Django 3.2.18 on 2023-05-09 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantillas', '0003_auto_20230508_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='fields',
        ),
        migrations.AddField(
            model_name='template',
            name='descrptn',
            field=models.CharField(default='NULL', max_length=50),
        ),
        migrations.AddField(
            model_name='template',
            name='descrptn_name',
            field=models.CharField(default='NULL', max_length=25),
        ),
        migrations.AddField(
            model_name='template',
            name='inccat',
            field=models.CharField(default='NULL', max_length=10),
        ),
    ]
