# Generated by Django 3.2.18 on 2023-04-14 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantillas', '0003_auto_20230414_1232'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='templatemonthlycfg',
            options={'ordering': ['date'], 'verbose_name': 'Ajuste de plantilla', 'verbose_name_plural': 'Ajustes de plantillas'},
        ),
        migrations.AlterModelOptions(
            name='templatemonthlycfglog',
            options={'ordering': ['created'], 'verbose_name': 'Resgistro de ajuste de plantilla', 'verbose_name_plural': 'Resgistros de ajustes de plantillas'},
        ),
        migrations.AlterField(
            model_name='templatelog',
            name='bldgid',
            field=models.CharField(max_length=10),
        ),
    ]
