# Generated by Django 3.2.18 on 2023-05-10 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plantillas', '0004_auto_20230509_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templatemonthlycfglog',
            name='rate',
        ),
        migrations.DeleteModel(
            name='TemplateMonthlyCfg',
        ),
        migrations.DeleteModel(
            name='TemplateMonthlyCfgLog',
        ),
    ]
