# Generated by Django 3.2.18 on 2023-04-17 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantillas', '0005_alter_templatelog_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatelog',
            name='username',
            field=models.CharField(default='Null', max_length=30),
        ),
        migrations.AlterField(
            model_name='templatelog',
            name='batch',
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
        ),
    ]
