# Generated by Django 3.2.18 on 2023-05-11 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToMri',
            fields=[
                ('cmbatch', models.CharField(max_length=10, verbose_name='CMBATCH')),
                ('item', models.IntegerField(primary_key=True, serialize=False, verbose_name='ITEM')),
                ('bldgid', models.CharField(max_length=10, verbose_name='BLDGID')),
                ('leasid', models.CharField(max_length=10, verbose_name='LEASID')),
                ('trandate', models.DateField(verbose_name='TRANDATE')),
                ('inccat', models.CharField(max_length=6, verbose_name='INCCAT')),
                ('srccode', models.CharField(default='CH', max_length=2, verbose_name='SRCCODE')),
                ('descrptn', models.CharField(max_length=50, verbose_name='DESCRPTN')),
                ('tranamt', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='TRANAMT')),
                ('chkdesc', models.CharField(default='', max_length=30, verbose_name='CHKDESC')),
                ('refnmbr', models.CharField(default='', max_length=30, verbose_name='REFNMBR')),
                ('taxmod', models.CharField(default='', max_length=30, verbose_name='TAXMOD')),
                ('rtaxamt', models.CharField(default='', max_length=30, verbose_name='RTAXAMT')),
                ('invoice', models.CharField(default='', max_length=30, verbose_name='INVOICE')),
                ('cashtype', models.CharField(default='', max_length=30, verbose_name='CASHTYPE')),
                ('taxitem', models.CharField(default='N', max_length=1, verbose_name='TAXITEM')),
                ('jobcode', models.CharField(default='', max_length=30, verbose_name='JOBCODE')),
                ('bankid', models.CharField(default='', max_length=30, verbose_name='BANKID')),
                ('retropd', models.CharField(default='', max_length=30, verbose_name='RETROPD')),
                ('rtaxgrpid', models.CharField(max_length=6, verbose_name='RTAXGRPID')),
                ('department', models.CharField(default='@', max_length=30, verbose_name='DEPARTMENT')),
                ('postorder', models.CharField(default='', max_length=30, verbose_name='POSTORDER')),
                ('currcode', models.CharField(max_length=3, verbose_name='CURRCODE')),
                ('bcurcode', models.CharField(default='DOP', max_length=3, verbose_name='BCURCODE')),
                ('bctranamt', models.CharField(default='', max_length=30, verbose_name='BCTRANAMT')),
                ('bcrtaxamt', models.CharField(default='', max_length=30, verbose_name='BCRTAXAMT')),
                ('bcexchgref', models.CharField(default='', max_length=30, verbose_name='BCEXCHGREF')),
                ('adjinvoice', models.CharField(default='', max_length=30, verbose_name='ADJINVOICE')),
                ('adjflag', models.CharField(default='', max_length=30, verbose_name='ADJFLAG')),
                ('wtaxid', models.CharField(default='', max_length=30, verbose_name='WTAXID')),
                ('recpttypeid', models.CharField(default='', max_length=30, verbose_name='RECPTTYPEID')),
                ('jc_phasecode', models.CharField(default='', max_length=30, verbose_name='JC_PHASECODE')),
                ('applyflag', models.CharField(default='', max_length=30, verbose_name='APPLYFLAG')),
                ('autoexception', models.CharField(default='', max_length=30, verbose_name='AUTOEXCEPTION')),
                ('recptno', models.CharField(default='', max_length=30, verbose_name='RECPTNO')),
                ('recptscreen', models.CharField(default='', max_length=30, verbose_name='RECPTSCREEN')),
                ('addldesc', models.CharField(default='', max_length=30, verbose_name='ADDLDESC')),
                ('sdtranid', models.CharField(default='', max_length=30, verbose_name='SDTRANID')),
            ],
            options={
                'verbose_name': 'Dato para MRI',
                'verbose_name_plural': 'Datos para MRI',
                'db_table': 'tomri_data',
                'ordering': ['item'],
            },
        ),
    ]
