# Generated by Django 3.2.18 on 2023-05-10 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToMri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmbatch', models.CharField(max_length=10)),
                ('item', models.IntegerField()),
                ('bldgid', models.CharField(max_length=10)),
                ('leasid', models.CharField(max_length=10)),
                ('trandate', models.DateField()),
                ('inccat', models.CharField(max_length=6)),
                ('srccode', models.CharField(default='CH', max_length=2)),
                ('descrptn', models.CharField(max_length=50)),
                ('tranamt', models.DecimalField(decimal_places=2, max_digits=9)),
                ('chkdesc', models.CharField(default='', max_length=30)),
                ('refnmbr', models.CharField(default='', max_length=30)),
                ('taxmod', models.CharField(default='', max_length=30)),
                ('rtaxamt', models.CharField(default='', max_length=30)),
                ('invoice', models.CharField(default='', max_length=30)),
                ('cashtype', models.CharField(default='', max_length=30)),
                ('taxitem', models.CharField(default='N', max_length=1)),
                ('jobcode', models.CharField(default='', max_length=30)),
                ('bankid', models.CharField(default='', max_length=30)),
                ('retropd', models.CharField(default='', max_length=30)),
                ('rtaxgrpid', models.CharField(max_length=6)),
                ('department', models.CharField(default='@', max_length=30)),
                ('postorder', models.CharField(default='', max_length=30)),
                ('currcode', models.CharField(max_length=3)),
                ('bcurcode', models.CharField(default='DOP', max_length=3)),
                ('bctranamt', models.CharField(default='', max_length=30)),
                ('bcrtaxamt', models.CharField(default='', max_length=30)),
                ('bcexchgref', models.CharField(default='', max_length=30)),
                ('adjinvoice', models.CharField(default='', max_length=30)),
                ('adjflag', models.CharField(default='', max_length=30)),
                ('wtaxid', models.CharField(default='', max_length=30)),
                ('recpttypeid', models.CharField(default='', max_length=30)),
                ('jc_phasecode', models.CharField(default='', max_length=30)),
                ('applyflag', models.CharField(default='', max_length=30)),
                ('autoexception', models.CharField(default='', max_length=30)),
                ('recptno', models.CharField(default='', max_length=30)),
                ('recptscreen', models.CharField(default='', max_length=30)),
                ('addldesc', models.CharField(default='', max_length=30)),
                ('sdtranid', models.CharField(default='', max_length=30)),
            ],
            options={
                'verbose_name': 'Dato para MRI',
                'verbose_name_plural': 'Datos para MRI',
                'db_table': 'tomri_data',
                'ordering': ['item'],
            },
        ),
    ]
