# Generated by Django 3.2.18 on 2023-05-12 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToMri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmbatch', models.CharField(db_column='CMBATCH', max_length=10)),
                ('item', models.IntegerField(db_column='ITEM')),
                ('bldgid', models.CharField(db_column='BLDGID', max_length=10)),
                ('leasid', models.CharField(db_column='LEASID', max_length=10)),
                ('trandate', models.DateField(db_column='TRANDATE')),
                ('inccat', models.CharField(db_column='INCCAT', max_length=6)),
                ('srccode', models.CharField(db_column='SRCCODE', default='CH', max_length=2)),
                ('descrptn', models.CharField(db_column='DESCRPTN', max_length=50)),
                ('tranamt', models.DecimalField(db_column='TRANAMT', decimal_places=2, max_digits=9)),
                ('chkdesc', models.CharField(db_column='CHKDESC', default='', max_length=30)),
                ('refnmbr', models.CharField(db_column='REFNMBR', default='', max_length=30)),
                ('taxmod', models.CharField(db_column='TAXMOD', default='', max_length=30)),
                ('rtaxamt', models.CharField(db_column='RTAXAMT', default='', max_length=30)),
                ('invoice', models.CharField(db_column='INVOICE', default='', max_length=30)),
                ('cashtype', models.CharField(db_column='CASHTYPE', default='', max_length=30)),
                ('taxitem', models.CharField(db_column='TAXITEM', default='N', max_length=1)),
                ('jobcode', models.CharField(db_column='JOBCODE', default='', max_length=30)),
                ('bankid', models.CharField(db_column='BANKID', default='', max_length=30)),
                ('retropd', models.CharField(db_column='RETROPD', default='', max_length=30)),
                ('rtaxgrpid', models.CharField(db_column='RTAXGRPID', max_length=6)),
                ('department', models.CharField(db_column='DEPARTMENT', default='@', max_length=30)),
                ('postorder', models.CharField(db_column='POSTORDER', default='', max_length=30)),
                ('currcode', models.CharField(db_column='CURRCODE', max_length=3)),
                ('bcurcode', models.CharField(db_column='BCURCODE', default='DOP', max_length=3)),
                ('bctranamt', models.CharField(db_column='BCTRANAMT', default='', max_length=30)),
                ('bcrtaxamt', models.CharField(db_column='BCRTAXAMT', default='', max_length=30)),
                ('bcexchgref', models.CharField(db_column='BCEXCHGREF', default='', max_length=30)),
                ('adjinvoice', models.CharField(db_column='ADJINVOICE', default='', max_length=30)),
                ('adjflag', models.CharField(db_column='ADJFLAG', default='', max_length=30)),
                ('wtaxid', models.CharField(db_column='WTAXID', default='', max_length=30)),
                ('recpttypeid', models.CharField(db_column='RECPTTYPEID', default='', max_length=30)),
                ('jc_phasecode', models.CharField(db_column='JC_PHASECODE', default='', max_length=30)),
                ('applyflag', models.CharField(db_column='APPLYFLAG', default='', max_length=30)),
                ('autoexception', models.CharField(db_column='AUTOEXCEPTION', default='', max_length=30)),
                ('recptno', models.CharField(db_column='RECPTNO', default='', max_length=30)),
                ('recptscreen', models.CharField(db_column='RECPTSCREEN', default='', max_length=30)),
                ('addldesc', models.CharField(db_column='ADDLDESC', default='', max_length=30)),
                ('sdtranid', models.CharField(db_column='SDTRANID', default='', max_length=30)),
            ],
            options={
                'verbose_name': 'Dato para MRI',
                'verbose_name_plural': 'Datos para MRI',
                'db_table': 'tomri_data',
                'ordering': ['item'],
            },
        ),
    ]
