# Generated by Django 3.2.18 on 2023-05-11 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_mri', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tomri',
            name='addldesc',
            field=models.CharField(db_column='ADDLDESC', default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='tomri',
            name='adjflag',
            field=models.CharField(db_column='ADJFLAG', default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='tomri',
            name='adjinvoice',
            field=models.CharField(db_column='ADJINVOICE', default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='tomri',
            name='applyflag',
            field=models.CharField(db_column='APPLYFLAG', default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='tomri',
            name='autoexception',
            field=models.CharField(db_column='AUTOEXCEPTION', default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='tomri',
            name='bankid',
            field=models.CharField(db_column='BANKID', default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='tomri',
            name='bcexchgref',
            field=models.CharField(db_column='BCEXCHGREF', default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='tomri',
            name='bcrtaxamt',
            field=models.CharField(db_column='BCRTAXAMT', default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='tomri',
            name='bctranamt',
            field=models.CharField(db_column='BCTRANAMT', default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='tomri',
            name='bcurcode',
            field=models.CharField(db_column='BCURCODE', default='DOP', max_length=3),
        ),
        migrations.AlterField(
            model_name='tomri',
            name='bldgid',
            field=models.CharField(db_column='BLDGID', max_length=10),
        ),
        migrations.AlterField(
            model_name='tomri',
            name='cashtype',
            field=models.CharField(db_column='CASHTYPE', default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='tomri',
            name='chkdesc',
            field=models.CharField(db_column='CHKDESC', default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='tomri',
            name='cmbatch',
            field=models.CharField(db_column='CMBATCH', max_length=10),
        ),
        migrations.AlterField(
            model_name='tomri',
            name='currcode',
            field=models.CharField(db_column='CURRCODE', max_length=3),
        ),
        migrations.AlterField(
            model_name='tomri',
            name='department',
            field=models.CharField(db_column='DEPARTMENT', default='@', max_length=30),
        ),
        migrations.AlterField(
            model_name='tomri',
            name='descrptn',
            field=models.CharField(db_column='DESCRPTN', max_length=50),
        ),
        migrations.AlterField(
            model_name='tomri',
            name='inccat',
            field=models.CharField(db_column='INCCAT', max_length=6),
        ),
        migrations.AlterField(
            model_name='tomri',
            name='invoice',
            field=models.CharField(db_column='INVOICE', default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='tomri',
            name='item',
            field=models.IntegerField(db_column='ITEM', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tomri',
            name='jc_phasecode',
            field=models.CharField(db_column='JC_PHASECODE', default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='tomri',
            name='jobcode',
            field=models.CharField(db_column='JOBCODE', default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='tomri',
            name='leasid',
            field=models.CharField(db_column='LEASID', max_length=10),
        ),
        migrations.AlterField(
            model_name='tomri',
            name='postorder',
            field=models.CharField(db_column='POSTORDER', default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='tomri',
            name='recptno',
            field=models.CharField(db_column='RECPTNO', default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='tomri',
            name='recptscreen',
            field=models.CharField(db_column='RECPTSCREEN', default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='tomri',
            name='recpttypeid',
            field=models.CharField(db_column='RECPTTYPEID', default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='tomri',
            name='refnmbr',
            field=models.CharField(db_column='REFNMBR', default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='tomri',
            name='retropd',
            field=models.CharField(db_column='RETROPD', default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='tomri',
            name='rtaxamt',
            field=models.CharField(db_column='RTAXAMT', default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='tomri',
            name='rtaxgrpid',
            field=models.CharField(db_column='RTAXGRPID', max_length=6),
        ),
        migrations.AlterField(
            model_name='tomri',
            name='sdtranid',
            field=models.CharField(db_column='SDTRANID', default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='tomri',
            name='srccode',
            field=models.CharField(db_column='SRCCODE', default='CH', max_length=2),
        ),
        migrations.AlterField(
            model_name='tomri',
            name='taxitem',
            field=models.CharField(db_column='TAXITEM', default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='tomri',
            name='taxmod',
            field=models.CharField(db_column='TAXMOD', default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='tomri',
            name='tranamt',
            field=models.DecimalField(db_column='TRANAMT', decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='tomri',
            name='trandate',
            field=models.DateField(db_column='TRANDATE'),
        ),
        migrations.AlterField(
            model_name='tomri',
            name='wtaxid',
            field=models.CharField(db_column='WTAXID', default='', max_length=30),
        ),
    ]
