# Generated by Django 3.2.18 on 2023-05-08 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_mri', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tomri',
            options={'ordering': ['item'], 'verbose_name': 'Dato para MRI', 'verbose_name_plural': 'Datos para MRI'},
        ),
        migrations.AlterModelTable(
            name='tomri',
            table='tomri_data',
        ),
    ]
