# Generated by Django 3.2.18 on 2023-05-12 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_mri', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tomri',
            name='id',
        ),
        migrations.AlterField(
            model_name='tomri',
            name='item',
            field=models.IntegerField(db_column='ITEM', primary_key=True, serialize=False),
        ),
    ]
