# Generated by Django 3.2.18 on 2023-05-09 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_mri', '0002_auto_20230508_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tomri',
            name='bcurcode',
            field=models.CharField(default='DOP', max_length=3),
        ),
    ]
