# Generated by Django 3.2.18 on 2023-05-10 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_mri', '0002_auto_20230510_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tomri',
            name='item',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='ITEM'),
        ),
    ]
