# Generated by Django 3.2.18 on 2023-03-23 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datosp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leasid', models.CharField(max_length=10)),
                ('bldgid', models.CharField(max_length=10)),
                ('suitid', models.CharField(max_length=10)),
                ('occpname', models.CharField(max_length=50)),
                ('values', models.JSONField(null=True)),
            ],
        ),
    ]
