# Generated by Django 3.2.18 on 2023-04-17 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leasid', models.CharField(max_length=10)),
                ('bldgid', models.CharField(max_length=10)),
                ('suitid', models.CharField(max_length=10)),
                ('occpname', models.CharField(max_length=50)),
                ('fields', models.JSONField(null=True)),
            ],
            options={
                'verbose_name': 'Dato de Plantilla',
                'verbose_name_plural': 'Datos de Plantillas',
                'db_table': 'templates_data',
                'ordering': ['bldgid'],
            },
        ),
        migrations.CreateModel(
            name='TemplateDataUploadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('bldgid', models.CharField(max_length=10)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Registro de subida',
                'verbose_name_plural': 'Registros de subida',
                'db_table': 'templates_data_upload_log',
                'ordering': ['bldgid'],
            },
        ),
        migrations.CreateModel(
            name='TemplateDataLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='Null', max_length=30)),
                ('first_validation', models.BooleanField(default=False)),
                ('second_validation', models.BooleanField(default=False)),
                ('created', models.DateTimeField()),
                ('bldgid', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='datos.templatedata')),
            ],
            options={
                'verbose_name': 'Registro de Dato',
                'verbose_name_plural': 'Registros de Datos',
                'db_table': 'templates_data_log',
                'ordering': ['bldgid'],
            },
        ),
    ]
