# Generated by Django 3.2.18 on 2023-03-27 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogDatosP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('building', models.CharField(max_length=10)),
                ('created', models.DateTimeField()),
            ],
        ),
    ]
