# Generated by Django 3.2.18 on 2023-03-27 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0002_logdatosp'),
    ]

    operations = [
        migrations.AddField(
            model_name='logdatosp',
            name='real',
            field=models.BooleanField(default=False),
        ),
    ]
