# Generated by Django 3.2.18 on 2023-04-19 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0002_alter_templatedatalog_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatedatalog',
            name='bldgid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datos.templatedata'),
        ),
    ]
