# Generated by Django 3.2.18 on 2023-04-04 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0003_logdatosp_real'),
    ]

    operations = [
        migrations.AddField(
            model_name='logdatosp',
            name='real2',
            field=models.BooleanField(default=False),
        ),
    ]
