# Generated by Django 3.2.18 on 2023-04-19 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0003_alter_templatedatalog_bldgid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatedatalog',
            name='bldgid',
            field=models.CharField(max_length=10),
        ),
    ]
