# Generated by Django 3.2.18 on 2023-04-12 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0004_logdatosp_real2'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogSubirDatosP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('building', models.CharField(max_length=10)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
