# Generated by Django 3.2.18 on 2023-05-11 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0004_alter_templatedatalog_bldgid'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatedata',
            name='cmbatch',
            field=models.CharField(default='NULL', max_length=10),
        ),
        migrations.AddField(
            model_name='templatedata',
            name='currcode',
            field=models.CharField(default='NULL', max_length=3),
        ),
        migrations.AddField(
            model_name='templatedata',
            name='rate',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=9),
        ),
    ]
