# Generated by Django 3.2.18 on 2023-05-11 21:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0005_auto_20230511_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatedata',
            name='trandate',
            field=models.DateField(default=datetime.datetime(2023, 5, 11, 17, 9, 25, 959761)),
        ),
    ]
