# Generated by Django 3.2.18 on 2023-05-11 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0006_templatedata_trandate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templatedata',
            name='trandate',
        ),
    ]
